package deltachat

// #cgo CFLAGS: -I../deltachat-ffi/include
// #cgo LDFLAGS: -L../deltachat-ffi/lib -ldeltachat
// #include <deltachat.h>
// #include <godeltachat.h>
import "C"

const (
	DC_MSG_ID_MARKER1                    = C.DC_MSG_ID_MARKER1
	DC_MSG_ID_DAYMARKER                  = C.DC_MSG_ID_DAYMARKER
	DC_MSG_ID_LAST_SPECIAL               = C.DC_MSG_ID_LAST_SPECIAL
	DC_MSG_TEXT                          = C.DC_MSG_TEXT
	DC_MSG_IMAGE                         = C.DC_MSG_IMAGE
	DC_MSG_GIF                           = C.DC_MSG_GIF
	DC_MSG_STICKER                       = C.DC_MSG_STICKER
	DC_MSG_AUDIO                         = C.DC_MSG_AUDIO
	DC_MSG_VOICE                         = C.DC_MSG_VOICE
	DC_MSG_VIDEO                         = C.DC_MSG_VIDEO
	DC_MSG_FILE                          = C.DC_MSG_FILE
	DC_LP_AUTH_OAUTH2                    = C.DC_LP_AUTH_OAUTH2
	DC_LP_AUTH_NORMAL                    = C.DC_LP_AUTH_NORMAL
	DC_LP_IMAP_SOCKET_STARTTLS           = C.DC_LP_IMAP_SOCKET_STARTTLS
	DC_LP_IMAP_SOCKET_SSL                = C.DC_LP_IMAP_SOCKET_SSL
	DC_LP_IMAP_SOCKET_PLAIN              = C.DC_LP_IMAP_SOCKET_PLAIN
	DC_LP_SMTP_SOCKET_STARTTLS           = C.DC_LP_SMTP_SOCKET_STARTTLS
	DC_LP_SMTP_SOCKET_SSL                = C.DC_LP_SMTP_SOCKET_SSL
	DC_LP_SMTP_SOCKET_PLAIN              = C.DC_LP_SMTP_SOCKET_PLAIN
	DC_LP_AUTH_FLAGS                     = C.DC_LP_AUTH_FLAGS
	DC_LP_IMAP_SOCKET_FLAGS              = C.DC_LP_IMAP_SOCKET_FLAGS
	DC_LP_SMTP_SOCKET_FLAGS              = C.DC_LP_SMTP_SOCKET_FLAGS
	DC_EVENT_INFO                        = C.DC_EVENT_INFO
	DC_EVENT_SMTP_CONNECTED              = C.DC_EVENT_SMTP_CONNECTED
	DC_EVENT_IMAP_CONNECTED              = C.DC_EVENT_IMAP_CONNECTED
	DC_EVENT_SMTP_MESSAGE_SENT           = C.DC_EVENT_SMTP_MESSAGE_SENT
	DC_EVENT_IMAP_MESSAGE_DELETED        = C.DC_EVENT_IMAP_MESSAGE_DELETED
	DC_EVENT_IMAP_MESSAGE_MOVED          = C.DC_EVENT_IMAP_MESSAGE_MOVED
	DC_EVENT_IMAP_FOLDER_EMPTIED         = C.DC_EVENT_IMAP_FOLDER_EMPTIED
	DC_EVENT_NEW_BLOB_FILE               = C.DC_EVENT_NEW_BLOB_FILE
	DC_EVENT_DELETED_BLOB_FILE           = C.DC_EVENT_DELETED_BLOB_FILE
	DC_EVENT_WARNING                     = C.DC_EVENT_WARNING
	DC_EVENT_ERROR                       = C.DC_EVENT_ERROR
	DC_EVENT_ERROR_NETWORK               = C.DC_EVENT_ERROR_NETWORK
	DC_EVENT_ERROR_SELF_NOT_IN_GROUP     = C.DC_EVENT_ERROR_SELF_NOT_IN_GROUP
	DC_EVENT_MSGS_CHANGED                = C.DC_EVENT_MSGS_CHANGED
	DC_EVENT_INCOMING_MSG                = C.DC_EVENT_INCOMING_MSG
	DC_EVENT_MSG_DELIVERED               = C.DC_EVENT_MSG_DELIVERED
	DC_EVENT_MSG_FAILED                  = C.DC_EVENT_MSG_FAILED
	DC_EVENT_MSG_READ                    = C.DC_EVENT_MSG_READ
	DC_EVENT_CHAT_MODIFIED               = C.DC_EVENT_CHAT_MODIFIED
	DC_EVENT_CONTACTS_CHANGED            = C.DC_EVENT_CONTACTS_CHANGED
	DC_EVENT_LOCATION_CHANGED            = C.DC_EVENT_LOCATION_CHANGED
	DC_EVENT_CONFIGURE_PROGRESS          = C.DC_EVENT_CONFIGURE_PROGRESS
	DC_EVENT_IMEX_PROGRESS               = C.DC_EVENT_IMEX_PROGRESS
	DC_EVENT_IMEX_FILE_WRITTEN           = C.DC_EVENT_IMEX_FILE_WRITTEN
	DC_EVENT_SECUREJOIN_INVITER_PROGRESS = C.DC_EVENT_SECUREJOIN_INVITER_PROGRESS
	DC_EVENT_SECUREJOIN_JOINER_PROGRESS  = C.DC_EVENT_SECUREJOIN_JOINER_PROGRESS
	DC_EVENT_SECUREJOIN_MEMBER_ADDED     = C.DC_EVENT_SECUREJOIN_MEMBER_ADDED
	DC_EVENT_FILE_COPIED                 = C.DC_EVENT_FILE_COPIED
	DC_EVENT_IS_OFFLINE                  = C.DC_EVENT_IS_OFFLINE
	DC_EVENT_GET_STRING                  = C.DC_EVENT_GET_STRING
)
